[package]
name = "chp8_crates"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true # enable debug symbols in release builds for testing!

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
